//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Account
    {
        public int AccountId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> HotelServiceId { get; set; }
        public Nullable<int> LokantaId { get; set; }
        public Nullable<decimal> Last_Account { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public Nullable<int> Personel_Number { get; set; }
        public Nullable<int> RoomId { get; set; }
    }
}
