//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDbEntities : DbContext
    {
        public HotelDbEntities()
            : base("name=HotelDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Customer_Account> Customer_Account { get; set; }
        public virtual DbSet<HotelService> HotelService { get; set; }
        public virtual DbSet<lokanta> lokanta { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
